export const SET_WASH_MACHINE = 'SET_WASH_MACHINE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_USER_LAUNDRY = 'GET_USER_LAUNDRY';
export const GET_ALL_LAUNDRY = 'GET_ALL_LAUNDRY';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const LIST_USER_MESSAGES = 'LIST_USER_MESSAGES';
export const GET_MESSAGE_TO_USER_FROM_USER = 'GET_MESSAGE_TO_USER_FROM_USER';
export const POST_MESSAGE_TO_USER_FROM_USER = 'POST_MESSAGE_TO_USER_FROM_USER';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const POST_INSTAGRAM_SYNC = 'POST_INSTAGRAM_SYNC';
export const POST_PASSWORD_RECOVERY = 'POST_PASSWORD_RECOVERY';
export const POST_PASSWORD_RECOVERY_BY_ID = 'POST_PASSWORD_RECOVERY_BY_ID';
export const POST_SET_LAUNDRY = 'POST_SET_LAUNDRY';
export const GET_LAST_USERS_KEY = 'GET_LAST_USERS_KEY';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


// 